const dishes = [
    { keyword: "borsh", name: "Борщ", price: 350, category: "soup", count: "250 гр", image: "images/борщ.jpg" },
    { keyword: "harcho", name: "Харчо", price: 340, category: "soup", count: "250 гр", image: "images/харчо.jpg"},
    { keyword: "chicken_soup", name: "Куриный суп", price: 240, category: "soup", count: "250 гр", image: "images/chicken_soup.jpg" },
    { keyword: "tomato_soup", name: "Томатный суп", price: 320, category: "soup", count: "300 гр", image: "images/Tomato_soup.jpg" },
    { keyword: "lentil_soup", name: "Суп из чечевицы", price: 300, category: "soup", count: "300 гр", image: "images/Lentil_soup.jpg" },
    { keyword: "yha", name: "Уха", price: 280, category: "soup", count: "300 гр", image: "images/yha.jpg" },
    { keyword: "salad_with_shrimp", name: "Салат с креветками и ананасом", price: 400, category: "salad", count: "250 гр", image: "images/salad_with_shrimp.jpg" },
    { keyword: "salad_with_squid", name: "Салат с кальмаром и пекинской капустой", price: 420, category: "salad", count: "250 гр", image: "images/Salad_with_squid.jpg" },
    { keyword: "salad_vegetable", name: "Овощной салат", price: 300, category: "salad", count: "250 гр", image: "images/vegetable_salad.jpg" },
    { keyword: "korean_salad", name: "Салат по-корейски", price: 360, category: "salad", count: "250 гр", image: "images/Korean_salad.jpg" },
    { keyword: "starter_Anti-paste", name: "Стартер Антипаста ", price: 330, category: "salad", count: "250 гр", image: "images/starter_Anti-paste.jpg" },
    { keyword: "starter_Bruschetta", name: "Брускетты", price: 280, category: "salad", count: "250 гр", image: "images/starte_Bruschetta.jpg" },
    { keyword: "homemade_stew", name: "Жаркое по-домашнему", price: 370, category: "main_dish", count: "300 гр", image: "images/homemade_stew.jpg" },
    { keyword: "pelmeni", name: "Пельмени со сметанной", price: 220, category: "main_dish", count: "200 гр", image: "images/пельмени.jpg" },
    { keyword: "beef_steak", name: "Стейк из говядины", price: 600, category: "main_dish", count: "300 гр", image: "images/steak.jpg" },
    { keyword: "fish_steak", name: "Рыбный стейк", price: 480, category: "main_dish", count: "250 гр", image: "images/Fish_steak.jpg" },
    { keyword: "risotto_cutlets", name: "Котлеты с ризотто", price: 460, category: "main_dish", count: "350 гр", image: "images/risotto_cutlets.jpg" },
    { keyword: "chicken_cutlets", name: "Куриные котлеты", price: 520, category: "main_dish", count: "400 гр", image: "images/Chicken_cutlets.jpg" },
    { keyword: "lemonade", name: "Лимонад", price: 220, category: "drink", count: "340 мл", image: "images/lemonade.jpg" },
    { keyword: "orange_juice", name: "Апельсиновый сок", price: 280, category: "drink", count: "340 мл", image: "images/orange_juice.jpg" },
    { keyword: "strawberry_milkshake", name: "Клубничный коктейль", price: 230, category: "drink", count: "300 мл", image: "images/коктейль.jpg" },
    { keyword: "milkshake", name: "Молочный коктейль", price: 250, category: "drink", count: "300 мл", image: "images/milkshake.jpg" },
    { keyword: "black_tea", name: "Чёрный чай", price: 200, category: "drink", count: "350 мл", image: "images/black_tea.jpg" },
    { keyword: "coffee", name: "Кофе", price: 200, category: "drink", count: "350 мл", image: "images/coffee.jpg" },
];
  